### ISSUE TITLE
Mobface ( character edit screen) bug

### ISSUE THREAD

**Issue by zack0529** [CookiePLMonster/SilentPatchGF#17]
![godfather character edit bug](https://user-images.githubusercontent.com/102886160/182212250-9ea42310-27d6-4863-ae14-34faed361ad3.png)

The game zooms to the character's gut in the character edit screen when you try to alter the face, or give him a hat or whatever.
Is there a fix?

**Comment by CookiePLMonster** [comment]
That's an issue of https://github.com/ThirteenAG/WidescreenFixesPack, SilentPatch does not introduce it.

**Comment by zack0529** [comment]
> That's an issue of https://github.com/ThirteenAG/WidescreenFixesPack, SilentPatch does not introduce it.

Installing both silentpatch and the widescreen fix fixed the issue. Thanks
