### ISSUE TITLE
no available french version game

### ISSUE THREAD

**Issue by mike86170** [CookiePLMonster/SilentPatchGF#2]
Hello
I have the french version of the game. Unfortunately your patch does not work. Is your patch compatible only with the English version?
thank you in advance.

**Comment by CookiePLMonster** [comment]
That's worrying... I made the patch in a way which **should** have made it compatible with any EXE, but it seems like it's not. I need to take a look at it soon.

For the time being, try to obtain an English EXE - that should help.

**Comment by mike86170** [comment]
thank you. If you want I can send the exe of the french version.

**Comment by CookiePLMonster** [comment]
Solved by 4d8c8dbe1f7571e2e26fbc036b546177716c134b. Please open a new issue if it still doesn't work.
