### ISSUE TITLE
Patch doesn't work with the italian version.

### ISSUE THREAD

**Issue by ghost** [CookiePLMonster/SilentPatchGF#3]
Hi, above all thanks for this patch.
Unfortunately seems to do not work with the italian version of the game.
Can you address this? 
Thanks a lot.

**Comment by CookiePLMonster** [comment]
Also seems to break with French and German versions, nasty... Though I kind of expect the real issue to be DRM, and not language versions.

**Comment by ghost** [comment]
I play with the original EXE.
German/English NO CD doesn't work with my version.
Italian NO CD doesn't exist.

**Comment by CookiePLMonster** [comment]
For the record, does it crash with SilentPatchGF.asi in game directory or just doesn't load the patch?

**Comment by ghost** [comment]
Just doesn't load.
Widescreen patch by Thirteenag just load fine.

**Comment by CookiePLMonster** [comment]
Oh, that's useful info! That makes it pretty obvious that I didn't account for DRM properly... I'll have to come up with some way to fix this soon and may need assistance checking if it works.

**Comment by ghost** [comment]
Thanks for your efforts ;)
Need the EXE?

**Comment by CookiePLMonster** [comment]
I don't need it yet, I'll post in this issue if I need it! Thanks!

**Comment by CookiePLMonster** [comment]
Solved by 4d8c8dbe1f7571e2e26fbc036b546177716c134b. Please open a new issue if it still doesn't work.
