### ISSUE TITLE
Dealing with DVD disk reading problem....

### ISSUE THREAD

**Issue by DrmnSamoLiu** [CookiePLMonster/SilentPatchGF#4]
Hi !
I know my problem have nothing to do with your great patch, but you are the only one I know who had RE'd The GodFather's exe file so I like to ask if I have any chance to have your help.

I'm using 64bit Win10 build 17134.
The problem is the game exe can't seem to check the game DVD correctly. Every time I launch the game, it gave me that "Please insert correct CD/DVD" warning. 
I'm sure I inserted the legit DVD and it can be read and install by windows, so my guess is the game exe file is calling the wrong system API to check DVD legitimacy.
Some very old solutions states that one have to change SATA driver from "SATA AHCI" to "Standard Dual Channel PCI IDE SATA", but after I tried it my win10 just crashed (Although I managed to rescue it).

I even tried to install the game in a 32bit XP virtual machine and attach my CD/DVD device to it, but it also failed to recognize the DVD.

I know this could be easily fixed with a No-CD crack, but we all know that game cracks are super dangerous.
Do you maybe know what's the real cause of this problem and how to patch the exe file to make the game check DVD correctly and launch?
Thank you so much!

**Comment by CookiePLMonster** [comment]
Since the game seems to use Safedisc, it's not a stretch to assume it's not going to work well. I would just bite the bullet and get a no-CD, especially since you own the legitimate game already.
