### ISSUE TITLE
Doesn't fully work

### ISSUE THREAD

**Issue by SuperSjoerdie** [CookiePLMonster/SilentPatchGF#5]
I'm not quite sure if I maybe did anything wrong. I managed to get the EA logo and the The Godfather logo on my screen, the first two things of the intro movie, after which I heard some sound of what comes after that and the movie simply skipped. I am however very pleased with the fact you came up with these great and elegant solutions, I can finally play the game again without having to disable the movies folder, which can probably greatly enhance the player experience of many players.
If you need any more information about my particular problem or if you've maybe got a fix please respond. Thanks in advance.
A grateful user.

**Comment by SuperSjoerdie** [comment]
I also can't see the paramount pictures part, for example, nor can I open the trailer.

**Comment by SuperSjoerdie** [comment]
Reading your prelude again and reflecting on my own copy had me figuring out that I've deleted most of the .vp6 files when trying to fix the game in the first place. I'll have a reinstall and I guess I'll be good to go. Thank you very much for this great patch.

**Comment by CookiePLMonster** [comment]
It is possible, yes - for intro movies, audio is separate from videos so by removing .vp6 files you did not touch the audios.
