### ISSUE TITLE
ASI loader:unable to load silentpathgf.asi,Error 998，both happend on English verison and taiwan version

### ISSUE THREAD

**Issue by NATO2000** [CookiePLMonster/SilentPatchGF#9]
Hello @CookiePLMonster    

Now,I  have tried both Taiwan Version and English Version on the Windows 7 x64 system
they are all  encountering with Error "ASI loader:unable to load silentpathgf.asi,error 998"

In order to download the English version of the godfather, I spent a whole day, but there are still errors, which makes me realize that the error code 998 may really have nothing to do with the game version.

I am counting on you now

![tim 20190209195420](https://user-images.githubusercontent.com/47445654/52522913-5c962000-2cc6-11e9-94ed-9bdbbd3de354.png)

The godfather English version
MD5     ：B0F6C40B44445E62EC5DC3B7ED13C2CA
SHA1    ：6C872AA432DB25B82CF33300E2B7CBF330512532
CRC32   ：35B167CA

Downloaded from http://www.legendsworld.net/site/download.php?mirror=3662#Download

The godfather Taiwan version
MD5     ：C7D8FD4C39107442B6A0F20E0EC2A0DB
SHA1    ：727CE80E9C46547B84EE94928A9E448D5617F828
CRC32   ：FD103AF0

**Comment by NATO2000** [comment]
heyheyhey! I  have find the reason!

@CookiePLMonster you are using "godfatherfix.rar" no cd patch right?

[Play Instructions:Install the game - Full Installation.Replace the original GODFATHER.EXE file with the one from the File Archive.Play the Game!
--
Note:This Fixed EXE fixes the problem of not getting out of cars! | Note: |   | This Fixed EXE fixes the problem of not getting out of cars!
Note: |   | This Fixed EXE fixes the problem of not getting out of cars!

The Godfather v1.0 [ENGLISH] Proper Fixed EXE
[link removed]



MD5     ：59C27503358F84FBFEC9C66EC8BA7D6E
SHA1    ：0F004E87A71B510FD226A2E50A517F82D70BF2CE
CRC32   ：1422F57D



I found only this no cd patch can use your SilentPatchGF 


this is my taiwan no cd patch
[link removed]

**Comment by CookiePLMonster** [comment]
Indeed, that's very likely to be the reason. There are multiple other bug reports about SPGF not working with regional EXEs and I didn't figure out why yet.

I removed the links from your post, since I don't want to share EXEs here.

**Comment by NATO2000** [comment]
if you really can't do   something to the no cd patchbut you can show me which files control the language，so i can change the language mysel  fat least i can try

**Comment by NATO2000** [comment]
Since I have a little experience on change language, in game text,but I would like to try

if you know how to change godfather 's in game language,please tell me, let me do the rest things

thank you very much!

**Comment by CookiePLMonster** [comment]
I am not really sure how to change language either, sorry.

**Comment by CookiePLMonster** [comment]
Solved by 4d8c8dbe1f7571e2e26fbc036b546177716c134b. Please open a new issue if it still doesn't work.
